---
- name: Check Jenkins Build Agents
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_ip: "44.223.48.234"
    jenkins_port: 8080  # Assuming default Jenkins port is used
    jenkins_user: "admin"
    jenkins_token: "118e1fc9091f867ce9a87f71505e3bb4b8"

  tasks:
    - name: Get Jenkins build agents status
      uri:
        url: "http://{{ jenkins_ip }}:{{ jenkins_port }}/computer/api/json"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_token }}"
        return_content: yes
      register: build_agents
      failed_when: build_agents.status != 200

    - name: Print build agents status
      debug:
        msg: "{{ item.displayName }}: {{ item.offline }}"
      with_items: "{{ build_agents.json.computer }}"
