---
- name: Pre-Checks for Jenkins Environment
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_ip: "44.223.48.234"
    jenkins_port: 8080
    git_command: "git --version"
    maven_command: "mvn --version"
    kubectl_command: "kubectl version --client"
    sonar_url: "http://10.138.77.104:9000"
    docker_registry_url: "https://hub.docker.com/u/bhavanaguda"

  tasks:
    - name: Check Available Memory on Jenkins Server
      shell: free -m | awk 'NR==2{print $7}'
      register: free_memory
      ignore_errors: yes

    - name: Check if Available Memory is Sufficient
      fail:
        msg: "Insufficient memory available on Jenkins server. Please allocate more memory."
      when: free_memory.stdout|int < 1000  # Adjust the threshold as needed

    - name: Check if Git is installed
      command: "{{ git_command }}"
      register: git_result
      ignore_errors: yes

    - name: git
      debug:
        msg: "Git is not installed."
      when: git_result is failed

    - name: Check if Maven is installed
      command: "{{ maven_command }}"
      register: maven_result
      ignore_errors: yes

    - name: maven
      debug:
        msg: "Maven is not installed."
      when: maven_result is failed

    - name: Check if Kubernetes is installed
      command: "{{ kubectl_command }}"
      register: kubectl_result
      ignore_errors: yes

    - name: Kubernetes
      debug:
        msg: "Kubernetes is not installed."
      when: kubectl_result is failed

    - name: Check if SonarQube is reachable
      uri:
        url: "{{ sonar_url }}"
        return_content: yes
        status_code: 200
      register: sonar_result
      ignore_errors: yes

    - name: SonarQube
      debug:
        msg: "SonarQube is not reachable."
      when: sonar_result.status != 200

    - name: Check if Docker Registry is reachable
      uri:
        url: "{{ docker_registry_url }}"
        return_content: yes
        status_code: 200
      register: docker_result
      ignore_errors: yes

    - name: Docker
      debug:
        msg: "Docker Registry is not reachable."
      when: docker_result.status != 200
