---
- name: Pre-Checks for Jenkins Environment
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_ip: "10.63.20.41"
    jenkins_port: 8080
    git_command: "git --version"
    maven_command: "mvn --version"
    kubectl_command: "kubectl version --client"
    sonar_url: "http://10.138.77.104:9000"
    docker_registry_url: "https://hub.docker.com/u/bhavanaguda"
    jenkins_user: "ramakanth"
    jenkins_token: "11224b5d9b915e9b6540e5fd11d87baf82"

  tasks:
    - name: Check if Git is installed
      command: "{{ git_command }}"
      register: git_result
      ignore_errors: yes

    - name: Print Git not installed message
      debug:
        msg: "Git is not installed."
      when: git_result is failed

    - name: Check Available Memory on Jenkins Server
      shell: free -m | awk 'NR==2{print $3}'   # Get used memory
      register: used_memory
      ignore_errors: yes

    - name: Check Total Memory on Jenkins Server
      shell: free -m | awk 'NR==2{print $2}'   # Get total memory
      register: total_memory
      ignore_errors: yes

    - name: Calculate remaining memory
      set_fact:
        remaining_memory: "{{ total_memory.stdout|int - used_memory.stdout|int }}"

    - name: Print message if remaining memory is less than 1GB
      debug:
        msg: "Insufficient memory available on Jenkins server. {{ remaining_memory }} MB left. Please allocate more memory."
      when: remaining_memory < 1024

    - name: Print message if remaining memory is sufficient
      debug:
        msg: "Sufficient memory available on Jenkins server. {{ remaining_memory }} MB left."
      when: remaining_memory >= 1024

    - name: Check if Maven is installed
      command: "{{ maven_command }}"
      register: maven_result
      ignore_errors: yes

    - name: Print Maven not installed message
      debug:
        msg: "Maven is not installed."
      when: maven_result is failed

    - name: Check if Kubernetes is installed
      command: "{{ kubectl_command }}"
      register: kubectl_result
      ignore_errors: yes

    - name: Print Kubernetes not installed message
      debug:
        msg: "Kubernetes is not installed."
      when: kubectl_result is failed

    - name: Check Jenkins Master-Slave connection
      uri:
        url: "http://{{ jenkins_ip }}:{{ jenkins_port }}/computer/api/json"
        method: GET
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_token }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: jenkins_connection
      ignore_errors: yes

    - name: Print connection status
      debug:
        msg: "Connection to Jenkins master-slave endpoint succeeded."
      when: jenkins_connection.status == 200

    - name: Print connection failed message
      debug:
        msg: "Connection to Jenkins master-slave endpoint failed."
      when: jenkins_connection.status != 200
