---
- name: Check Jenkins Master-Slave Connection Problems
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_url: "http://jenkins_master:8080"
    slave_name: "my-slave"

  tasks:
    - name: Check Jenkins Master-Slave connection
      uri:
        url: "{{ jenkins_url }}/computer/{{ slave_name }}/api/json"
        method: GET
        return_content: yes
      register: slave_status
      ignore_errors: yes

    - name: Ensure Slave is online
      fail:
        msg: "Slave {{ slave_name }} is not online or unreachable."
      when: slave_status.json.offline == true or slave_status.failed
      tags: connection_check
