---
- name: Pre-Checks for Jenkins Environment
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_url: "http://jenkins_master:8080"
    slave_name: "my-slave"
    git_command: "git --version"
    maven_command: "mvn --version"
    kubectl_command: "kubectl version --client"
    sonar_url: "http://10.138.77.104:9000"
    docker_registry_url: "https://hub.docker.com/u/bhavanaguda"

  tasks:
    - name: Check Jenkins Master-Slave connection
      uri:
        url: "{{ jenkins_url }}/computer/{{ slave_name }}/api/json"
        method: GET
        return_content: yes
      register: slave_status
      ignore_errors: yes

    - name: Ensure Slave is online
      fail:
        msg: "Slave {{ slave_name }} is not online or unreachable."
      when: slave_status | failed or slave_status.status != 200 or ('json' in slave_status.content and slave_status.json.offline == true)
      tags: connection_check

    - name: Check if Git is installed
      command: "{{ git_command }}"
      register: git_result
      ignore_errors: yes

    - name: git
      debug:
        msg: "Git is not installed."
      when: git_result is failed

    - name: Check if Maven is installed
      command: "{{ maven_command }}"
      register: maven_result
      ignore_errors: yes

    - name: maven
      debug:
        msg: "Maven is not installed."
      when: maven_result is failed

    - name: Check if Kubernetes is installed
      command: "{{ kubectl_command }}"
      register: kubectl_result
      ignore_errors: yes

    - name: Kubernetes
      debug:
        msg: "Kubernetes is not installed."
      when: kubectl_result is failed

    - name: Check if SonarQube is reachable
      uri:
        url: "{{ sonar_url }}"
        return_content: yes
        status_code: 200
      register: sonar_result
      ignore_errors: yes

    - name: SonarQube
      debug:
        msg: "SonarQube is not reachable."
      when: sonar_result.status != 200

    - name: Check if Docker Registry is reachable
      uri:
        url: "{{ docker_registry_url }}"
        return_content: yes
        status_code: 200
      register: docker_result
      ignore_errors: yes

    - name: Docker
      debug:
        msg: "Docker Registry is not reachable."
      when: docker_result.status != 200

