---
- name: Check Jenkins Build Agents
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_url: "http://44.223.48.234:8080/"
    jenkins_user: "admin"
    jenkins_token: "11ba504ff33f0b10643ee54e7b3068f1ac"

  tasks:
    - name: Get Jenkins build agents status
      uri:
        url: "{{ jenkins_url }}/computer/api/json"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_token }}"
        return_content: yes
      register: build_agents
      failed_when: build_agents.status != 200

    - name: Print build agents status
      debug:
        msg: "{{ item.displayName }}: {{ item.offline }}"
      with_items: "{{ build_agents.json.computer }}"
