---
- name: Check Jenkins Master-Slave Connection
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_ip: "44.223.48.234"
    jenkins_port: 8080
    jenkins_admin_user: "admin"
    jenkins_admin_token: "118e1fc9091f867ce9a87f71505e3bb4b8"

  tasks:
    - name: Check Jenkins Master-Slave connection
      uri:
        url: "http://{{ jenkins_ip }}:{{ jenkins_port }}/computer/api/json"
        user: "{{ jenkins_admin_user }}"
        password: "{{ jenkins_admin_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: jenkins_connection
      ignore_errors: yes

    - name: Print connection status
      debug:
        msg: "Connection to Jenkins master-slave endpoint succeeded."
      when: jenkins_connection.status == 200

    - name: Print connection failed message
      debug:
        msg: "Connection to Jenkins master-slave endpoint failed."
      when: jenkins_connection.status != 200
